Repository canonical/github-runner-image-builder, pull requests merged in 2024-11, with the labels that each got.

#38 chore: log image snapshot errors
  pyproject.toml
  src/github_runner_image_builder/openstack_builder.py
  src/github_runner_image_builder/store.py
Labels: trivial

#39 feat: external script
  pyproject.toml
  src-docs/config.md
  src-docs/openstack_builder.md
  src-docs/store.md
  src/github_runner_image_builder/cli.py
  src/github_runner_image_builder/config.py
  src/github_runner_image_builder/openstack_builder.py
  src/github_runner_image_builder/templates/cloud-init.sh.j2
  tests/integration/commands.py
  tests/integration/test_image.py
  tests/integration/test_openstack_builder.py
  tests/integration/testdata/test_script.sh
  tests/unit/test_openstack_builder.py
Labels: enhancement, complex, senior-review-required

#40 feat: external secret
  src-docs/cli.md
  src-docs/config.md
  src/github_runner_image_builder/cli.py
  src/github_runner_image_builder/config.py
  src/github_runner_image_builder/openstack_builder.py
  src/github_runner_image_builder/templates/cloud-init.sh.j2
  tests/integration/commands.py
  tests/integration/test_openstack_builder.py
  tests/integration/testdata/test_script.sh
  tests/unit/test_cli.py
  tests/unit/test_openstack_builder.py
Labels: enhancement, senior-review-required

#41 Decrease min ram requirements for openstack builder
  pyproject.toml
  src/github_runner_image_builder/openstack_builder.py
Labels: trivial
